version: '{build}'
platform: Any CPU
configuration: Release
init:
  # For tagged releases, use tag name as version
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        $versionNumber = $($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))
        Write-Host "Setting build version to $versionNumber"
        Update-AppveyorBuild -Version "$versionNumber"
      }
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe
before_build:
  - cd Source && nuget restore
build:
  publish_nuget: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
nuget:
  disable_publish_on_pr: true
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: P7/VG8DnNs9JW9dCjNnLmtto46T/WD0P+Jf1L6KY+UawIdMpo2glsAfgWNMVge/R
  on:
    appveyor_repo_tag: true
